# Generated by Django 5.1.5 on 2025-07-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
