# Generated by Django 5.1.5 on 2025-07-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailnotification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
