# Generated by Django 5.1.5 on 2025-07-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_emailnotification_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
