# Generated by Django 5.1.5 on 2025-12-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_emailnotification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotificationtype',
            name='notification_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Informe de tráfico'), (2, 'Webhook cancelado')], unique=True),
        ),
    ]
