# Generated by Django 5.1.5 on 2026-02-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_emailnotificationtype_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotificationtype',
            name='notification_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Informe de tráfico'), (2, 'Webhook cancelado'), (3, 'Informe de ventas')], unique=True),
        ),
    ]
