# Generated by Django 5.1.5 on 2025-02-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmessage',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
