# Generated by Django 5.1.5 on 2025-03-05 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0002_notificationmessage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('month', models.DateField()),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
