# Generated by Django 5.1.5 on 2025-03-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0003_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmessage',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
