# Generated by Django 5.1.5 on 2025-07-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0006_canvasmessage_appprice_canvaslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='appprice',
            name='app',
            field=models.CharField(default=1, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='canvaslog',
            name='app',
            field=models.CharField(default=2, max_length=50),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='app',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
