# Generated by Django 5.1.5 on 2025-07-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0007_appprice_app_canvaslog_app_notificationlog_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='app',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
