# Generated by Django 5.1.5 on 2025-07-07 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0009_trafficevent_executionlog_trafficlog_executionprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExecutionPrice',
        ),
    ]
