# Generated by Django 5.1.5 on 2025-07-08 02:52

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0010_delete_executionprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('date', models.DateField(help_text='Fecha para la cual se establece la meta', unique=True)),
                ('target_count', models.IntegerField(help_text='Meta de count esperada para el día', validators=[django.core.validators.MinValueValidator(0)])),
                ('app', models.CharField(default=3, max_length=50)),
            ],
            options={
                'verbose_name': 'Meta Diaria',
                'verbose_name_plural': 'Metas Diarias',
                'ordering': ['-date'],
            },
        ),
    ]
