# Generated by Django 5.1.5 on 2025-12-20 19:21

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0011_dailymeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('payload', models.JSONField(help_text='JSON payload recibido del webhook')),
                ('source', models.CharField(blank=True, help_text='Origen o servicio que envió el webhook', max_length=100, null=True)),
                ('event_type', models.CharField(blank=True, help_text='Tipo de evento del webhook', max_length=100, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('app', models.CharField(default=5, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
