# Generated by Django 5.1.5 on 2025-12-23 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0012_webhooklog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='comment',
            field=models.TextField(blank=True, help_text='Comentario sobre el webhook', null=True),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la edición', null=True),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='edited_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que editó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_webhooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='is_edited',
            field=models.BooleanField(default=False, help_text='Indica si el registro ya fue editado (solo se puede editar una vez)'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='poc',
            field=models.CharField(blank=True, help_text='Punto de venta de origen', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='repurchased',
            field=models.BooleanField(default=False, help_text='Indica si el cliente volvió a comprar'),
        ),
    ]
