# Generated by Django 5.1.5 on 2026-01-06 22:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0013_webhooklog_comment_webhooklog_edited_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('id_poc', models.CharField(help_text='Unique POC identifier', max_length=100, unique=True)),
                ('city', models.CharField(help_text='City in Ecuador', max_length=100)),
                ('name', models.CharField(help_text='POC name', max_length=255)),
                ('region', models.CharField(choices=[('costa', 'Costa'), ('sierra', 'Sierra'), ('oriente', 'Oriente'), ('insular', 'Insular')], help_text='Region: Costa, Sierra, Oriente, or Insular', max_length=20)),
                ('homologated_names', models.JSONField(blank=True, default=list, help_text='List of alternative/homologated names for matching purposes')),
            ],
            options={
                'verbose_name': 'POC',
                'verbose_name_plural': 'POCs',
                'db_table': 'tada_poc',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id_poc'], name='tada_poc_id_poc_3a3e0b_idx'), models.Index(fields=['city'], name='tada_poc_city_c22f06_idx'), models.Index(fields=['region'], name='tada_poc_region_62cffe_idx')],
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('principal', 'Principal'), ('combo', 'Combo')], default='principal', help_text='SKU type: principal or combo', max_length=20)),
                ('vendor_code', models.CharField(help_text='Vendor code', max_length=100)),
                ('sku_vtex', models.CharField(help_text='VTEX SKU (unique)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('units', models.IntegerField(default=1, help_text='Number of units')),
                ('milliliters_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Milliliters per unit', max_digits=10, null=True)),
                ('units_per_box', models.IntegerField(blank=True, help_text='Number of units per box', null=True)),
                ('hectoliters_per_unit', models.DecimalField(blank=True, decimal_places=6, help_text='Hectoliters per unit', max_digits=10, null=True)),
                ('hectoliters_per_box', models.DecimalField(blank=True, decimal_places=6, help_text='Hectoliters per box', max_digits=10, null=True)),
                ('homologated_names', models.JSONField(blank=True, default=list, help_text='List of alternative/homologated names for matching purposes')),
                ('child_skus', models.ManyToManyField(blank=True, help_text='Child SKUs that compose this combo (only applies if type=combo)', related_name='parent_skus', to='tada.sku')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKUs',
                'db_table': 'tada_sku',
                'ordering': ['-created_at'],
            },
        ),
    ]
