# Generated by Django 5.1.5 on 2026-01-07 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0014_poc_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('filename', models.CharField(help_text='Nombre del archivo procesado', max_length=500)),
                ('rows_processed', models.IntegerField(default=0, help_text='Cantidad de filas procesadas')),
                ('date', models.DateField(help_text='Fecha del procesamiento')),
                ('time', models.TimeField(help_text='Hora del procesamiento')),
                ('app', models.CharField(help_text='App asociada (SALES)', max_length=50)),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que procesó el reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_report_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-date', '-time'], name='tada_salesr_date_6f24e3_idx'), models.Index(fields=['app'], name='tada_salesr_app_7fde70_idx'), models.Index(fields=['user'], name='tada_salesr_user_id_6322e3_idx')],
            },
        ),
    ]
