# Generated by Django 5.1.5 on 2026-01-07 19:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0015_salesreportlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentasProductosApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('principal', 'Principal'), ('combo', 'Combo')], default='principal', help_text='Product type: principal or combo', max_length=20)),
                ('code', models.CharField(help_text='Unique product SKU code', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('unit', models.IntegerField(default=1, help_text='Quantity/units')),
            ],
            options={
                'verbose_name': 'Ventas Producto App',
                'verbose_name_plural': 'Ventas Productos App',
                'db_table': 'tada_ventas_productos_app',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VentasProductosCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('code', models.CharField(help_text='Unique product code', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('homologated_names', models.JSONField(blank=True, default=list, help_text='List of alternative/homologated names for matching purposes')),
                ('mililiters_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Milliliters per unit', max_digits=10, null=True)),
                ('box_units', models.IntegerField(blank=True, help_text='Number of units per box', null=True)),
                ('primary_can', models.CharField(blank=True, help_text='Primary can type', max_length=255, null=True)),
                ('returnable', models.BooleanField(default=False, help_text='Whether the product is returnable')),
                ('origen', models.CharField(blank=True, choices=[('importado', 'Importado'), ('nacional', 'Nacional')], help_text='Product origin: imported or national', max_length=20, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit', max_digits=12, null=True)),
                ('cost_per_box', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per box', max_digits=12, null=True)),
                ('cost_per_hectoliter', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per hectoliter', max_digits=12, null=True)),
                ('brand', models.CharField(blank=True, help_text='Product brand', max_length=255, null=True)),
                ('category', models.CharField(blank=True, help_text='Product category', max_length=255, null=True)),
                ('hectoliter_per_unit', models.DecimalField(blank=True, decimal_places=6, help_text='Hectoliters per unit (e.g., 0.1)', max_digits=10, null=True)),
                ('hectoliter_box', models.DecimalField(blank=True, decimal_places=6, help_text='Hectoliters per box', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Venta Producto Compra',
                'verbose_name_plural': 'Ventas Productos Compra',
                'db_table': 'tada_ventas_productos_compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VentasProductosAppMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of this material used', max_digits=10)),
                ('ventas_productos_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_items', to='tada.ventasproductosapp')),
                ('ventas_productos_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_apps', to='tada.ventasproductoscompra')),
            ],
            options={
                'verbose_name': 'Ventas Productos App Material',
                'verbose_name_plural': 'Ventas Productos App Materials',
                'db_table': 'tada_ventas_productos_app_material',
                'unique_together': {('ventas_productos_app', 'ventas_productos_compra')},
            },
        ),
        migrations.AddField(
            model_name='ventasproductosapp',
            name='materials',
            field=models.ManyToManyField(blank=True, help_text='Materials that compose this product', related_name='app_products', through='tada.VentasProductosAppMaterial', to='tada.ventasproductoscompra'),
        ),
        migrations.DeleteModel(
            name='SKU',
        ),
    ]
