# Generated by Django 5.1.5 on 2026-01-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0016_ventasproductosapp_ventasproductoscompra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreportlog',
            name='processing_time_seconds',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Tiempo de procesamiento en segundos (para cálculo de precio)', max_digits=10, null=True),
        ),
    ]
