# Generated by Django 5.1.5 on 2026-01-09 22:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0017_salesreportlog_processing_time_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HectolitresDailyMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('date', models.DateField(help_text='Fecha para la cual se establece la meta de hectolitros', unique=True)),
                ('target_hectolitres', models.DecimalField(decimal_places=2, help_text='Meta de hectolitros esperada para el día', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('app', models.CharField(default=6, max_length=50)),
            ],
            options={
                'verbose_name': 'Meta Diaria de Hectolitros',
                'verbose_name_plural': 'Metas Diarias de Hectolitros',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('date', models.DateField(help_text='Fecha de la venta')),
                ('store_name', models.CharField(help_text='Nombre original de la tienda del Excel', max_length=255)),
                ('sku_vtex', models.CharField(help_text='SKU del material final (después de expansión)', max_length=100)),
                ('poc_id', models.CharField(blank=True, max_length=100, null=True)),
                ('poc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('poc_homolo', models.CharField(blank=True, help_text='Nombre homologado si difiere del nombre principal', max_length=255, null=True)),
                ('poc_city', models.CharField(blank=True, max_length=100, null=True)),
                ('poc_region', models.CharField(blank=True, max_length=100, null=True)),
                ('sku_padre', models.CharField(max_length=100)),
                ('nombre_padre', models.CharField(blank=True, max_length=255, null=True)),
                ('orders', models.IntegerField(default=0, help_text='Número de pedidos')),
                ('units', models.IntegerField(default=0, help_text='Unidades vendidas del producto padre')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_homologated', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('retornable', models.CharField(blank=True, max_length=50, null=True)),
                ('units_assigned', models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad del material en el producto padre', max_digits=10, null=True)),
                ('units_per_sku', models.DecimalField(blank=True, decimal_places=4, help_text='Unidades vendidas del material (units * units_assigned)', max_digits=10, null=True)),
                ('unidades_por_caja', models.IntegerField(blank=True, null=True)),
                ('venta_pack', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('mililitros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hectolitros', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('dolars', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('dayname', models.CharField(blank=True, max_length=20, null=True)),
                ('year_month', models.CharField(blank=True, max_length=10, null=True)),
                ('sales_log', models.ForeignKey(help_text='Log del procesamiento que generó este registro', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tada.salesreportlog')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que procesó el reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'poc_name', 'sku_vtex'],
                'indexes': [models.Index(fields=['date', 'store_name', 'sku_vtex'], name='tada_salesr_date_7ef014_idx'), models.Index(fields=['-date'], name='tada_salesr_date_89edb8_idx'), models.Index(fields=['poc_id'], name='tada_salesr_poc_id_507c7e_idx'), models.Index(fields=['sku_padre'], name='tada_salesr_sku_pad_7c10c7_idx'), models.Index(fields=['sku_vtex'], name='tada_salesr_sku_vte_b9fa5b_idx'), models.Index(fields=['sales_log'], name='tada_salesr_sales_l_30e1a9_idx'), models.Index(fields=['year', 'month'], name='tada_salesr_year_ac2de8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('date', 'store_name', 'sku_vtex'), name='unique_sale_record')],
            },
        ),
    ]
