# Generated by Django 5.1.5 on 2026-01-10 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0018_hectolitresdailymeta_salesrecord'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesrecord',
            name='unique_sale_record',
        ),
    ]
