# Generated by Django 5.1.5 on 2026-01-10 22:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0019_remove_salesrecord_unique_sale_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecordQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('query_type', models.CharField(choices=[('list', 'Lista/Consulta'), ('download', 'Descarga Excel')], help_text='Tipo de consulta realizada', max_length=50)),
                ('records_returned', models.IntegerField(default=0, help_text='Cantidad de registros SalesRecord devueltos en la consulta')),
                ('filters_applied', models.JSONField(blank=True, help_text='Filtros aplicados en la consulta (start_date, end_date, poc_name, etc.)', null=True)),
                ('date', models.DateField(help_text='Fecha de la consulta')),
                ('time', models.TimeField(help_text='Hora de la consulta')),
                ('app', models.CharField(default=7, help_text='App asociada (SALES_CHECK)', max_length=50)),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que realizó la consulta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_query_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-date', '-time'], name='tada_salesr_date_775386_idx'), models.Index(fields=['app'], name='tada_salesr_app_ffceae_idx'), models.Index(fields=['user'], name='tada_salesr_user_id_a19a98_idx'), models.Index(fields=['query_type'], name='tada_salesr_query_t_51c690_idx')],
            },
        ),
    ]
