# Generated by Django 5.1.5 on 2026-01-15 14:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0020_salesrecordquerylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('date_processed', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del procesamiento')),
                ('initrowdate', models.DateField(help_text='Fecha inicial de los datos procesados')),
                ('endrowdate', models.DateField(help_text='Fecha final de los datos procesados')),
                ('rows_count', models.IntegerField(default=0, help_text='Cantidad total de registros procesados')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que procesó el reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_upload_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_processed'],
                'indexes': [models.Index(fields=['-date_processed'], name='tada_salesu_date_pr_2a44c4_idx'), models.Index(fields=['initrowdate', 'endrowdate'], name='tada_salesu_initrow_05bb0e_idx')],
            },
        ),
    ]
