# Generated by Django 5.1.5 on 2026-01-19 14:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0021_salesuploadlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hectolitresdailymeta',
            name='target_hectolitres',
            field=models.DecimalField(decimal_places=3, help_text='Meta de hectolitros esperada para el día', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
