# Generated by Django 5.1.5 on 2026-01-29 17:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0022_alter_hectolitresdailymeta_target_hectolitres'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegativosJustificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('id_ticket', models.CharField(help_text='Unique ticket identifier', max_length=100, unique=True)),
                ('titulo_caso', models.CharField(help_text='Case title', max_length=500)),
                ('hora_inicio', models.DateTimeField(help_text='Case start time')),
                ('hora_fin', models.DateTimeField(help_text='Case end time')),
                ('justificacion', models.TextField(help_text='Justification text for the negative case')),
                ('es_tienda', models.BooleanField(default=False, help_text='Whether the case is related to a store/POC')),
                ('poc', models.ForeignKey(blank=True, help_text='Related POC/store if es_tienda is True', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negativos_justificaciones', to='tada.poc')),
            ],
            options={
                'verbose_name': 'Negativo Justificación',
                'verbose_name_plural': 'Negativos Justificaciones',
                'db_table': 'negativos_justificacion',
                'ordering': ['-hora_inicio'],
                'indexes': [models.Index(fields=['id_ticket'], name='negativos_j_id_tick_8e79f8_idx'), models.Index(fields=['hora_inicio'], name='negativos_j_hora_in_946cd7_idx'), models.Index(fields=['-hora_inicio'], name='negativos_j_hora_in_fc918b_idx')],
            },
        ),
    ]
