# Generated by Django 5.1.5 on 2026-01-29 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0023_negativosjustificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='negativosjustificacion',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this justification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negativos_justificaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
