# Generated by Django 5.1.5 on 2026-02-02 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0024_negativosjustificacion_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualYearlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('year', models.IntegerField(help_text='Año del dato histórico', verbose_name='Año')),
                ('start_week', models.IntegerField(help_text='Semana inicial del rango (1-53)', verbose_name='Semana Inicial')),
                ('end_week', models.IntegerField(help_text='Semana final del rango (1-53)', verbose_name='Semana Final')),
                ('report_type', models.CharField(choices=[('hectolitros', 'Hectolitros'), ('caja', 'Caja')], help_text='Tipo de dato: hectolitros o caja', max_length=20, verbose_name='Tipo de Reporte')),
                ('city', models.CharField(blank=True, help_text='Ciudad específica. Si es NULL, representa el total general', max_length=100, null=True, verbose_name='Ciudad')),
                ('value', models.DecimalField(decimal_places=2, help_text='Valor del dato histórico', max_digits=12, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Dato Anual Manual',
                'verbose_name_plural': 'Datos Anuales Manuales',
                'db_table': 'manual_yearly_data',
                'ordering': ['-year', 'start_week'],
                'indexes': [models.Index(fields=['year', 'start_week', 'end_week'], name='manual_year_year_b3772a_idx'), models.Index(fields=['report_type'], name='manual_year_report__e6fc39_idx'), models.Index(fields=['city'], name='manual_year_city_7080a4_idx')],
                'unique_together': {('year', 'start_week', 'end_week', 'report_type', 'city')},
            },
        ),
    ]
