# Generated by Django 5.1.5 on 2026-02-05 16:26

import core.utils.storage_backend
import django.db.models.deletion
import tada.models.salesFileStorage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0025_manualyearlydata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesFileStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('file', models.FileField(help_text='Archivo Excel original subido', storage=core.utils.storage_backend.PublicUploadStorage(), upload_to=tada.models.salesFileStorage.sales_file_upload_path)),
                ('filename', models.CharField(help_text='Nombre original del archivo', max_length=500)),
                ('file_size', models.BigIntegerField(help_text='Tamaño del archivo en bytes')),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 hash del contenido del archivo', max_length=64)),
                ('content_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 hash del contenido de datos (sin headers)', max_length=64, null=True)),
                ('date_range_start', models.DateField(blank=True, help_text='Fecha más antigua en el archivo', null=True)),
                ('date_range_end', models.DateField(blank=True, help_text='Fecha más reciente en el archivo', null=True)),
                ('total_rows', models.IntegerField(default=0, help_text='Total de filas de datos en el archivo')),
                ('unique_stores', models.IntegerField(default=0, help_text='Cantidad de tiendas únicas')),
                ('unique_skus', models.IntegerField(default=0, help_text='Cantidad de SKUs únicos')),
                ('processed', models.BooleanField(default=False, help_text='Si el archivo ya fue procesado')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Fecha/hora de procesamiento', null=True)),
                ('previous_file', models.ForeignKey(blank=True, help_text='Archivo anterior para comparación de diferencias', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_files', to='tada.salesfilestorage')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que subió el archivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de Ventas',
                'verbose_name_plural': 'Archivos de Ventas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesFileRowHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('row_key', models.CharField(db_index=True, help_text='Clave única: date|store|sku_padre|sku_material', max_length=500)),
                ('row_hash', models.CharField(help_text='SHA-256 hash del contenido de la fila', max_length=64)),
                ('date', models.DateField(help_text='Fecha de la fila')),
                ('store_name', models.CharField(help_text='Nombre de tienda', max_length=255)),
                ('sku', models.CharField(help_text='SKU del producto', max_length=100)),
                ('units', models.IntegerField(default=0, help_text='Unidades')),
                ('orders', models.IntegerField(default=0, help_text='Órdenes')),
                ('sales_file', models.ForeignKey(help_text='Archivo al que pertenece esta fila', on_delete=django.db.models.deletion.CASCADE, related_name='row_hashes', to='tada.salesfilestorage')),
            ],
            options={
                'verbose_name': 'Hash de Fila',
                'verbose_name_plural': 'Hashes de Filas',
                'ordering': ['date', 'store_name', 'sku'],
            },
        ),
        migrations.AddIndex(
            model_name='salesfilestorage',
            index=models.Index(fields=['-created_at'], name='tada_salesf_created_3ca0aa_idx'),
        ),
        migrations.AddIndex(
            model_name='salesfilestorage',
            index=models.Index(fields=['file_hash'], name='tada_salesf_file_ha_b0733e_idx'),
        ),
        migrations.AddIndex(
            model_name='salesfilestorage',
            index=models.Index(fields=['content_hash'], name='tada_salesf_content_7aeb24_idx'),
        ),
        migrations.AddIndex(
            model_name='salesfilestorage',
            index=models.Index(fields=['date_range_start', 'date_range_end'], name='tada_salesf_date_ra_4246ba_idx'),
        ),
        migrations.AddIndex(
            model_name='salesfilestorage',
            index=models.Index(fields=['processed'], name='tada_salesf_process_ca0e35_idx'),
        ),
        migrations.AddIndex(
            model_name='salesfilerowhash',
            index=models.Index(fields=['sales_file', 'row_key'], name='tada_salesf_sales_f_8d96a3_idx'),
        ),
        migrations.AddIndex(
            model_name='salesfilerowhash',
            index=models.Index(fields=['row_key'], name='tada_salesf_row_key_cac937_idx'),
        ),
        migrations.AddIndex(
            model_name='salesfilerowhash',
            index=models.Index(fields=['date'], name='tada_salesf_date_ee9b42_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesfilerowhash',
            constraint=models.UniqueConstraint(fields=('sales_file', 'row_key'), name='unique_file_row_key'),
        ),
    ]
