# Generated by Django 5.1.5 on 2026-02-06 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0026_salesfilestorage_salesfilerowhash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlySalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('date', models.DateField(help_text='Fecha del registro de venta', verbose_name='Fecha')),
                ('city', models.CharField(blank=True, help_text='Ciudad específica. Si es NULL, representa el total general', max_length=100, null=True, verbose_name='Ciudad')),
                ('total', models.DecimalField(decimal_places=2, help_text='Valor total de ventas (hectolitros o cajas según report_type)', max_digits=12, verbose_name='Total')),
                ('report_type', models.CharField(choices=[('hectolitros', 'Hectolitros'), ('caja', 'Caja')], default='hectolitros', help_text='Tipo de dato: hectolitros o caja', max_length=20, verbose_name='Tipo de Reporte')),
            ],
            options={
                'verbose_name': 'Dato de Venta Anual',
                'verbose_name_plural': 'Datos de Ventas Anuales',
                'ordering': ['-date', 'city'],
            },
        ),
        migrations.DeleteModel(
            name='ManualYearlyData',
        ),
        migrations.AddIndex(
            model_name='yearlysalesdata',
            index=models.Index(fields=['date', 'city', 'report_type'], name='tada_yearly_date_583b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='yearlysalesdata',
            index=models.Index(fields=['date', 'report_type'], name='tada_yearly_date_3b5ef9_idx'),
        ),
    ]
