# Generated by Django 5.1.5 on 2026-03-09 12:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0027_yearlysalesdata_delete_manualyearlydata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialItemsLegacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('fecha', models.DateField(help_text='Fecha del registro legacy')),
                ('nombre', models.CharField(help_text='Nombre del ítem/producto legacy', max_length=255)),
                ('hectolitros', models.DecimalField(decimal_places=4, default=0, help_text='Volumen en hectolitros', max_digits=14)),
                ('cajas', models.DecimalField(decimal_places=4, default=0, help_text='Cantidad en cajas', max_digits=14)),
            ],
            options={
                'verbose_name': 'Ítem Especial Legacy',
                'verbose_name_plural': 'Ítems Especiales Legacy',
                'ordering': ['-fecha', 'nombre'],
            },
        ),
    ]
