# Generated by Django 5.1.5 on 2026-03-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0028_specialitemslegacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='numero_orden',
            field=models.CharField(blank=True, help_text='Número de orden relacionado al webhook', max_length=100, null=True),
        ),
    ]
