# Generated by Django 5.1.5 on 2025-02-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_session_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
