# Generated by Django 5.1.5 on 2025-02-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_httpmethod_role_alter_customuser_managers_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', to='authentication.permission'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='methods',
            field=models.ManyToManyField(related_name='permissions', to='authentication.httpmethod'),
        ),
    ]
